# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
#      - name: Deploy Stage
#        uses: fjogeleit/http-request-action@v1
#        with:
#          url: 'https://api.github.com/repos/xuqiu/MyLeetCode'
#          method: 'GET'
#          username: ${{ secrets.AWX_USER }}
#          password: ${{ secrets.AWX_PASSWORD }}
#          customHeaders: '{"Content-Type": "application/json"}'
#          data: '{"key_1": "value_1", "key_2": "value_2"}'
#
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://api.github.com/repos/xuqiu/MyLeetCode"
          method: 'GET'
      - name: Show Response
        run: |
          echo ${{ steps.myRequest.outputs.response }}
          echo ${{ steps.myRequest.outputs.headers }}
          echo ${{ fromJson(steps.myRequest.outputs.response).description }}